# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/HMACSerialiser.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/HMACSerialiser.csproj

    - name: Test HMAC
      run: dotnet test --no-build --configuration Release --verbosity normal ./tests/HMACTests/HMACTests.csproj
    - name: Test HKDF
      run: dotnet test --no-build --configuration Release --verbosity normal ./tests/HKDFTests/HKDFTests.csproj
    - name: Test Base64 Encoders
      run: dotnet test --no-build --configuration Release --verbosity normal ./tests/Base64EncoderTests/Base64EncoderTests.csproj
